image: cypress/browsers:node18.12.0-chrome107

stages:
  - test

cache:
  paths:
    - node_modules/

cypress_tests:
  stage: test

  before_script:
    - npm install
    # ✅ garante que as pastas existam (evita erro de artifact)
    - mkdir -p cypress/reports
    - mkdir -p cypress/screenshots
    - mkdir -p cypress/videos

  script:
    - npx cypress run --browser chrome

  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
      - cypress/reports/
    expire_in: 7 days