image: cypress/browsers:node18.12.0-chrome107

stages:
  - test

cache:
  paths:
    - node_modules/

cypress_tests:
  stage: test

  before_script:
    - npm install

  script:
    - npx cypress run --browser chrome

  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 7 days