image: cypress/browsers:node18.12.0-chrome107

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/Cypress/

cypress_tests:
  stage: test

  before_script:
    - npm ci || npm install
    - npx cypress verify

  script:
    - npx cypress run --browser chrome

  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 7 days