name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Smoke Tests on Push
        if: github.event_name == 'push'
        run: npx cypress run --browser chrome --env TAGS='@smoke'

      - name: Run Regression Tests on Pull Request
        if: github.event_name == 'pull_request'
        run: npx cypress run --browser chrome --env TAGS='@regression'

      - name: Upload Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports